title: analogwgwhc
url: https://gwgwhc.github.io/
baseurl: 

author: George Hudson-Chang
description: description of the project

include: ['_pages']

collections_dir: series

collections:
  home:
    output: true
  images:
    output: true
  trees:
    output: true
  faces:
    output: true

markdown: kramdown
kramdown:
  input: GFM
